### PR TITLE
Hotfix/v1.1.2

### PR DESCRIPTION
**Pull request by nunofrsilva**
Hi Thank you for your plugin  👍 

Please consider to applying these changes, I only check if the types have extensions, if not remove the type from types array and fix the string "You can upload: Image, audio, ..."  this way the user only sees the types configured in backoffice

Thank you 👍

### CODE REVIEW

**Comment by yadenis** [comment]
Hello @nunofrsilva,

Thank you for your report and PR.

I created an issue #18 for this bug.

About your code.

**Check if extension is empty**
I don't quite understand why verification `!empty($ext)`  is needed. Can you please tell your case?

**Remove types without extensions**
- `unset` only affected for html format. Maybe we should move this check to the html section?
- I suggest replacing `foreach` with `array_filter`. Perhaps this will increase the clarity of this piece of code.

An example of my implementation:
```
if ( 'html' === $format ) {
	$types = array_filter(
		$types,
		function( $item ) {
			return count( $item['exts'] );
		}
	);

	$types_arr = array();
	foreach ( $types as $type ) {
		$title       = implode( ', ', $type['exts'] );
		$types_arr[] = '<abbr title="' . esc_attr( $title ) . '">' . esc_html( $type['name'] ) . '</abbr>';
	}

	$types = implode( ', ', $types_arr );
}
```
What do you think about this?

**Comment by nunofrsilva** [comment]
Hi @yadenis ,

Thank you for your support!

**Check if extension is empty**
I only use this validation `!empty($ext)` because some times I receive a mime with empty string  and you add this mime to Type of other.
**Example:**
```
$mimes = {array} [11]
 0 = "jpg|jpeg"
 1 = "gif"
 2 = "png"
 3 = ""
 4 = "txt"
 5 = "csv"
 6 = "pdf"
 7 = "doc"
 8 = "docx"
 9 = "odt"
 10 = "pages"
```

**Remove types without extensions**
In this case, your implementation is better, honestly I did not notice the following code
```
	if ( 'html' === $format ) {
		foreach ( $types as $type ) {
			$title       = implode( ', ', $type['exts'] );
			$types_arr[] = '<abbr title="' . esc_attr( $title ) . '">' . esc_html( $type['name'] ) . '</abbr>';
		}
		$types = implode( ', ', $types_arr );
	}
```

Thank you for your support!

**Comment by yadenis** [comment]
> I only use this validation !empty($ext) because some times I receive a mime with empty string and you add this mime to Type of other.

Sorry, but I can’t repeat it :(. Can you please create an issue and describe the steps to reproduce it?

> In this case, your implementation is better

Can you please send me this change with a separate PR? Then I can merge it. You can also specify your wp.org login, if you have a wp account, then I can mention you in the plugin changelog.

**Comment by nunofrsilva** [comment]
Hi @yadenis,

> Sorry, but I can’t repeat it :(. Can you please create an issue and describe the steps to reproduce it?

To reproduce this issue, you need to disable all extensions of a type, for example, go to the settings plugin and disable all video extensions.

> Can you please send me this change with a separate PR?

Sure I can send you a new PR, Thanks :)
For this bug, I was just thinking of adding an if to the existing loop. I think the array_filter is another unnecessary loop, because we already have one to show extensions in html.

```
	if ( 'html' === $format ) {
		$types_arr = array();
		foreach ( $types as $type ) {
                    if (!empty($type['exts'])) {
                        $title = implode(', ', $type['exts']);
                        $types_arr[] = '<abbr title="' . esc_attr($title) . '">' . esc_html($type['name']) . '</abbr>';
                    }
		}
		$types = implode( ', ', $types_arr );
	}

```
What do you think about this?

Thank you for your support!

**Comment by yadenis** [comment]
Hi @nunofrsilva,

> To reproduce this issue, you need to disable all extensions of a type, for example, go to the settings plugin and disable all video extensions.

Yes, I see. Thank you. I think this is the bug in `filter_upload_mimes` function in `DCO_CA` class. And probably we can fix it like this:
```
foreach ( $mimes as $mime => $mime_type ) {
	$exts = explode( '|', $mime );
	if ( count( $exts ) > 1 ) {
		$ext_items = array();
		foreach ( $exts as $ext ) {
			if ( in_array( $ext, $allowed_mimes, true ) ) {
				$ext_items[] = $ext;
			}
		}
		if( $ext_items ) {
			$exts                    = implode( '|', $ext_items );
			$filtered_mimes[ $exts ] = $mime_type;
		}
	} else {
		if ( in_array( $mime, $allowed_mimes, true ) ) {
			$filtered_mimes[ $mime ] = $mime_type;
		}
	}
}
```
I added `if( $ext_items ) {` check.

> I think the array_filter is another unnecessary loop, because we already have one to show extensions in html.

Yes, it's is a good idea! :) I would only replace `if (!empty($type['exts'])) {` with `if ( $type['exts'] ) {`. It should be simpler and equivalent.

If you agree with my suggestions, can you please send me a PR with changes in `filter_upload_mimes` and `get_allowed_file_types` functions?

**Pull request closed without merging**
